function [B,B_u,B_l] = FSquirrle_bases(R1,R2,R3,A11,A12,A21,A22,A31,A32,C1_u1,C1_u2,C1_u3,C2_u1,C2_u2,C2_u3,C3_u1,C3_u2,C3_u3)
%FSquirrle_bases
%    [B,B_u,B_l] = FSquirrle_bases(R1,R2,R3,A11,A12,A21,A22,A31,A32,C1_u1,C1_u2,C1_u3,C2_u1,C2_u2,C2_u3,C3_u1,C3_u2,C3_u3)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Apr-2025 19:06:37

t2 = C1_u3+R3;
t3 = C2_u3+R3;
t4 = C3_u3+R3;
t5 = -A11;
t6 = -A12;
t7 = -A21;
t8 = -A22;
t9 = -A31;
t10 = -A32;
t11 = t2.^2;
t12 = t3.^2;
t13 = t4.^2;
t14 = C1_u1+R1+t5;
t15 = C1_u2+R2+t6;
t16 = C2_u1+R1+t7;
t17 = C2_u2+R2+t8;
t18 = C3_u1+R1+t9;
t19 = C3_u2+R2+t10;
t20 = t14.^2;
t21 = t15.^2;
t22 = t16.^2;
t23 = t17.^2;
t24 = t18.^2;
t25 = t19.^2;
t26 = t20+t21;
t27 = t22+t23;
t28 = t24+t25;
t29 = t11+t26;
t30 = t12+t27;
t31 = t13+t28;
t32 = 1.0./sqrt(t26);
t33 = 1.0./sqrt(t27);
t34 = 1.0./sqrt(t28);
t35 = 1.0./sqrt(t29);
t36 = 1.0./sqrt(t30);
t37 = 1.0./sqrt(t31);
t38 = t14.*t32;
t39 = t15.*t32;
t40 = t16.*t33;
t41 = t17.*t33;
t42 = t18.*t34;
t43 = t19.*t34;
t44 = t2.*t35;
t45 = t3.*t36;
t46 = t4.*t37;
t47 = -t38;
t48 = -t39;
t49 = -t40;
t50 = -t41;
t51 = -t42;
t52 = -t43;
t56 = t14.*t35;
t57 = t15.*t35;
t58 = t16.*t36;
t59 = t17.*t36;
t60 = t18.*t37;
t61 = t19.*t37;
t53 = -t44;
t54 = -t45;
t55 = -t46;
t62 = -t56;
t63 = -t57;
t64 = -t58;
t65 = -t59;
t66 = -t60;
t67 = -t61;
B = reshape([t47+t62,t48+t63,t53,t49+t64,t50+t65,t54,t51+t66,t52+t67,t55,0.0,0.0,1.0],[3,4]);
if nargout > 1
    B_u = reshape([t62,t63,t53,t64,t65,t54,t66,t67,t55,0.0,0.0,0.0],[3,4]);
end
if nargout > 2
    B_l = reshape([t47,t48,0.0,t49,t50,0.0,t51,t52,0.0,0.0,0.0,1.0],[3,4]);
end
end
