function J_inv = FSquirrle_Jacobian_inverse(R1,R2,R3,A11,A12,A21,A22,A31,A32,C1_u1,C1_u2,C1_u3,C2_u1,C2_u2,C2_u3,C3_u1,C3_u2,C3_u3,r_p,p_s)
%FSquirrle_Jacobian_inverse
%    J_inv = FSquirrle_Jacobian_inverse(R1,R2,R3,A11,A12,A21,A22,A31,A32,C1_u1,C1_u2,C1_u3,C2_u1,C2_u2,C2_u3,C3_u1,C3_u2,C3_u3,R_P,P_S)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    04-Apr-2025 13:45:59

t2 = C1_u3+R3;
t3 = C2_u3+R3;
t4 = C3_u3+R3;
t5 = -A11;
t6 = -A12;
t7 = -A21;
t8 = -A22;
t9 = -A31;
t10 = -A32;
t11 = 1.0./r_p;
t12 = t2.^2;
t13 = t3.^2;
t14 = t4.^2;
t15 = C1_u1+R1+t5;
t16 = C1_u2+R2+t6;
t17 = C2_u1+R1+t7;
t18 = C2_u2+R2+t8;
t19 = C3_u1+R1+t9;
t20 = C3_u2+R2+t10;
t21 = t15.^2;
t22 = t16.^2;
t23 = t17.^2;
t24 = t18.^2;
t25 = t19.^2;
t26 = t20.^2;
t27 = t21+t22;
t28 = t23+t24;
t29 = t25+t26;
t30 = t12+t27;
t31 = t13+t28;
t32 = t14+t29;
t33 = 1.0./sqrt(t27);
t34 = 1.0./sqrt(t28);
t35 = 1.0./sqrt(t29);
t36 = 1.0./sqrt(t30);
t37 = 1.0./sqrt(t31);
t38 = 1.0./sqrt(t32);
J_inv = reshape([-t11.*(t15.*t33+t15.*t36),-t11.*(t17.*t34+t17.*t37),-t11.*(t19.*t35+t19.*t38),0.0,-t11.*(t16.*t33+t16.*t36),-t11.*(t18.*t34+t18.*t37),-t11.*(t20.*t35+t20.*t38),0.0,-t2.*t11.*t36,-t3.*t11.*t37,-t4.*t11.*t38,(pi.*2.0)./p_s],[4,3]);
end
